# Generated by Django 4.1.2 on 2023-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numder', models.IntegerField()),
                ('description', models.TextField()),
                ('L01', models.FloatField()),
                ('R01', models.FloatField()),
            ],
        ),
    ]
