# Generated by Django 4.1.2 on 2023-04-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='numder',
            new_name='number',
        ),
    ]
