# Generated by Django 4.1.2 on 2023-05-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_l01_variants_l1_rename_r01_variants_r1'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='F',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='Voltage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
